//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.11 at 08:31:32 PM IST 
//


package xmlParser.jaxbobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlParser.jaxbobjects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Deals_QNAME = new QName("", "deals");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlParser.jaxbobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Deals }
     * 
     */
    public Deals createDeals() {
        return new Deals();
    }

    /**
     * Create an instance of {@link DrawDown }
     * 
     */
    public DrawDown createDrawDown() {
        return new DrawDown();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link Deal }
     * 
     */
    public Deal createDeal() {
        return new Deal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Deals }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deals")
    public JAXBElement<Deals> createDeals(Deals value) {
        return new JAXBElement<Deals>(_Deals_QNAME, Deals.class, null, value);
    }

}
