//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 01:12:49 PM IST 
//


package webservices.beans.createdeals;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the webservices.beans.createdeals package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DrawDownAmount_QNAME = new QName("http://webservices/beans/createDeals", "amount");
    private final static QName _DrawDownDescription_QNAME = new QName("http://webservices/beans/createDeals", "description");
    private final static QName _DealDescrption_QNAME = new QName("http://webservices/beans/createDeals", "descrption");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: webservices.beans.createdeals
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DrawDown }
     * 
     */
    public DrawDown createDrawDown() {
        return new DrawDown();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link CreateDealsRequest }
     * 
     */
    public CreateDealsRequest createCreateDealsRequest() {
        return new CreateDealsRequest();
    }

    /**
     * Create an instance of {@link Deal }
     * 
     */
    public Deal createDeal() {
        return new Deal();
    }

    /**
     * Create an instance of {@link ResponseList }
     * 
     */
    public ResponseList createResponseList() {
        return new ResponseList();
    }

    /**
     * Create an instance of {@link CreateDealsResponse }
     * 
     */
    public CreateDealsResponse createCreateDealsResponse() {
        return new CreateDealsResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices/beans/createDeals", name = "amount", scope = DrawDown.class)
    public JAXBElement<Double> createDrawDownAmount(Double value) {
        return new JAXBElement<Double>(_DrawDownAmount_QNAME, Double.class, DrawDown.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices/beans/createDeals", name = "description", scope = DrawDown.class)
    public JAXBElement<String> createDrawDownDescription(String value) {
        return new JAXBElement<String>(_DrawDownDescription_QNAME, String.class, DrawDown.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices/beans/createDeals", name = "amount", scope = Facility.class)
    public JAXBElement<Double> createFacilityAmount(Double value) {
        return new JAXBElement<Double>(_DrawDownAmount_QNAME, Double.class, Facility.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices/beans/createDeals", name = "descrption", scope = Deal.class)
    public JAXBElement<String> createDealDescrption(String value) {
        return new JAXBElement<String>(_DealDescrption_QNAME, String.class, Deal.class, value);
    }

}
