//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 01:12:49 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices/beans/createDeals", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package webservices.beans.createdeals;
